package ed;

import androidx.constraintlayout.core.motion.utils.TypedValues;
import com.ironsource.Q6;
import com.mbridge.msdk.foundation.download.core.DownloadCommon;
import com.mbridge.msdk.mbbid.out.BidResponsed;
import com.unity3d.services.ads.gmascar.utils.ScarConstants;
import io.bidmachine.ads.networks.adaptiverendering.measurer.AdMeasurerFactory;
import java.util.HashMap;
import java.util.Map;

/* JADX INFO: compiled from: LanguageCodeLookup.java */
/* JADX INFO: loaded from: classes2.dex */
public class t {

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static final Map<String, String> f61094a;

    static {
        HashMap map = new HashMap();
        f61094a = map;
        map.put("en", "English");
        map.put("hi", "हिंदी");
        map.put("ml", "മലയാളം");
        map.put("ta", "தமிழ்");
        map.put("te", "తెలుగు");
        map.put("zh", "中文");
        map.put("fr", "Français");
        map.put(DownloadCommon.DOWNLOAD_REPORT_DOWNLOAD_ERROR, "Deutsch");
        map.put("sp", "Español");
        map.put("mr", "मराठी");
        map.put(ScarConstants.BN_SIGNAL_KEY, "বাংলা");
        map.put("gu", "ગુજરાતી");
        map.put("ur", "اردو");
        map.put("kn", "ಕನ್ನಡ");
        map.put("or", "ଓଡ଼ିଆ");
        map.put("pa", "پنجابی");
        map.put("sa", "संस्कृत");
        map.put("af", "Afrikaans");
        map.put("agq", "Aghem");
        map.put("ak", "Akan");
        map.put("am", "አማርኛ");
        map.put("ar", "العربية");
        map.put("as", "অসমীয়া");
        map.put("asa", "Kipare");
        map.put("ast", "asturianu");
        map.put("az", "azərbaycan");
        map.put("bas", "Ɓàsàa");
        map.put("be", "беларуская");
        map.put("bem", "Ichibemba");
        map.put("bez", "Hibena");
        map.put("bg", "български");
        map.put("bm", "bamanakan");
        map.put("bo", "བོད་སྐད་");
        map.put("br", "brezhoneg་");
        map.put("brx", "बड़ो་");
        map.put("bs", "bosanski་");
        map.put(DownloadCommon.DOWNLOAD_REPORT_CANCEL, "català་");
        map.put("ce", "нохчийн");
        map.put("cgg", "Rukiga");
        map.put("chr", "ᏣᎳᎩ");
        map.put("ckb", "کوردیی ناوەندی");
        map.put("cs", "čeština");
        map.put("cy", "Cymraeg");
        map.put("da", "dansk");
        map.put("dav", "Kitaita");
        map.put("dje", "Zarmaciine");
        map.put("dsb", "dolnoserbšćina");
        map.put("dua", "duálá");
        map.put("dyo", "joola");
        map.put("dz", "རྫོང་ཁ");
        map.put("ebu", "Kĩembu");
        map.put("ee", "Eʋegbe");
        map.put("el", "Ελληνικά");
        map.put("eo", "esperanto");
        map.put("es", "Español(América Latina)");
        map.put("es-ES", "Español(España)");
        map.put("et", "eesti");
        map.put("eu", "euskara");
        map.put("ewo", "ewondo");
        map.put("fa", "فارسی");
        map.put("ff", "Pulaar");
        map.put("fi", "suomi");
        map.put("fil", "Filipino");
        map.put("fo", "føroyskt");
        map.put("fur", "furlan");
        map.put("fy", "Frysk");
        map.put("ga", "Gaeilge");
        map.put("gd", "Gàidhlig");
        map.put("gl", "galego");
        map.put("gsw", "Schwiizertüütsch");
        map.put("guz", "Ekegusii");
        map.put("gv", "Gaelg");
        map.put("ha", "Hausa");
        map.put("haw", "ʻŌlelo Hawaiʻi");
        map.put("he", "עברית");
        map.put("hr", "hrvatski");
        map.put("hsb", "hornjoserbšćina");
        map.put("hu", "magyar");
        map.put("hy", "հայերեն");
        map.put("id", "Indonesia");
        map.put("ig", "Igbo");
        map.put("is", "íslenska");
        map.put("it", "italiano");
        map.put("ja", "日本語");
        map.put("jgo", "Ndaꞌa");
        map.put("jmc", "Kimachame");
        map.put("ka", "ქართული");
        map.put("kab", "Taqbaylit");
        map.put("kam", "Kikamba");
        map.put("kde", "Chimakonde");
        map.put("kea", "kabuverdianu");
        map.put("khq", "Koyra ciini");
        map.put("ki", "Gikuyu");
        map.put("kk", "қазақ тілі");
        map.put("kkj", "kakɔ");
        map.put("kl", "kalaallisut");
        map.put("kln", "Kalenjin");
        map.put("km", "ខ្មែរ");
        map.put("ko", "한국어");
        map.put("kok", "कोंकणी");
        map.put("ks", "کٲشُر");
        map.put("ksb", "Kishambaa");
        map.put("ksf", "rikpa");
        map.put("ksh", "Kölsch");
        map.put("kw", "kernewek");
        map.put("ky", "кыргызча");
        map.put("lag", "Kɨlaangi");
        map.put("lb", "Lëtzebuergesch");
        map.put("lg", "Luganda");
        map.put("lkt", "Lakȟólʼiyapi");
        map.put(BidResponsed.KEY_LN, "lingála");
        map.put("lo", "ລາວ");
        map.put("lrc", "لۊری شومالی");
        map.put("lt", "lietuvių");
        map.put("lu", "Tshiluba");
        map.put("luo", "Dholuo");
        map.put("luy", "Luluhia");
        map.put("lv", "latviešu");
        map.put("mas", "Maa");
        map.put("mer", "Kĩmĩrũ");
        map.put("mfe", "kreol morisien");
        map.put("mg", "Malagasy");
        map.put("mgh", "Makua");
        map.put("mgo", "metaʼ");
        map.put("mk", "македонски");
        map.put("mn", "монгол");
        map.put("ms", "Melayu");
        map.put(Q6.f30210a1, "Malti");
        map.put("mua", "MUNDAŊ");
        map.put("my", "မြန်မာ");
        map.put("mzn", "مازرونی");
        map.put("naq", "Khoekhoegowab");
        map.put("nb", "norsk bokmål");
        map.put("nd", "isiNdebele");
        map.put("ne", "नेपाली");
        map.put("nl", "Nederlands");
        map.put("nn", "nynorsk");
        map.put(AdMeasurerFactory.OM, "Oromoo");
        map.put(Q6.F, "ирон");
        map.put("pl", "polski");
        map.put("ps", "پښتو");
        map.put("pt", "português");
        map.put("qu", "Runasimi");
        map.put("rm", "rumantsch");
        map.put("rn", "Ikirundi");
        map.put("ro", "română");
        map.put("ru", "русский");
        map.put("rw", "Kinyarwanda");
        map.put("se", "davvisámegiella");
        map.put(Q6.f30237j1, "Sängö");
        map.put("shi", "ⵜⴰⵛⵍⵃⵉⵜ");
        map.put("si", "සිංහල");
        map.put("sk", "slovenčina");
        map.put("sl", "slovenščina");
        map.put("sn", "chiShona");
        map.put("so", "Soomaali");
        map.put("sq", "shqip");
        map.put("sr", "српски");
        map.put("sv", "svenska");
        map.put("sw", "Kiswahili");
        map.put("teo", "Kiteso");
        map.put("tg", "тоҷикӣ");
        map.put("th", "ไทย");
        map.put("ti", "ትግርኛ");
        map.put(TypedValues.TransitionType.S_TO, "lea fakatonga");
        map.put("tr", "Türkçe");
        map.put("tt", "татар");
        map.put("ug", "ئۇيغۇرچە");
        map.put("uk", "українська");
        map.put("uz", "o‘zbek");
        map.put("vai", "ꕙꔤ");
        map.put("vi", "Tiếng Việt");
        map.put("wo", "Wolof");
        map.put("yi", "ייִדיש");
        map.put("yo", "Èdè Yorùbá");
        map.put("zu", "isiZulu");
    }

    public static String a(String str) {
        String str2 = f61094a.get(str);
        return str2 != null ? str2 : str;
    }
}
